name: Release to Docker and git
on:
  release:
    types: [published, created, edited]
    branch: 
      - v*
#on: [push, pull_request]
jobs:
  test: 
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: test-enviroment
        run: |
          echo $GITHUB_REF
  docker:
    name: Release on Docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: cr-hn-1.vccloud.vn
          name: cr-hn-1.vccloud.vn/e221625fe113449d8360f6ead78fb884/bizfly-cloud-controller-manager:v0.1.1
          username: ${{ secrets.USER_CLOUD }}
          password: ${{ secrets.PASS }}
  git:
    name: Release on Git
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Validates GO releaser config
        uses: docker://goreleaser/goreleaser:latest
        with:
          args: check
      - name: Create release on GitHub
        uses: docker://goreleaser/goreleaser:latest
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
